### ISSUE TITLE
your discord-clone does not work in my computer.

### ISSUE THREAD

**Issue by sydrock1204** [devdimer/discord-clone#1]
I did install your discord using docker. But in middle of installing I met such errors:
![28 06 2024_18 42 08_REC](https://github.com/devdimer/discord-clone/assets/166016042/61bcfbb2-d1df-4fe1-9cb4-320f987c694d)

**Comment by henriquemdimer** [comment]
Hello, thanks for opening this issue, I tried to reproduce this error on my machine, but I couldn't, but I'm going to change the build system to Vite, as react-scripts is basically obsolete, as soon as I finish I'll let you know here and if you want you can try running it on your machine again.

**Comment by sydrock1204** [comment]
Thank you. What is your gmail? I wanna dedicate your project.
